/**
 * CAM LABS — Comprehensive Engineering Materials Database
 * Real-world mechanical properties, tolerances, and process parameters
 */

const MATERIALS_DATA = [
  {
    id: "pa12-sls",
    name: "PA 12 (Nylon 12)",
    technology: "SLS",
    category: "Polymers",
    description: "Versatile engineering thermoplastic with balanced mechanical properties, high chemical resistance, and excellent fatigue resistance.",
    tensileStrength: 48, // MPa
    hdt: 175, // °C @ 0.45 MPa
    elongation: 18, // %
    density: 1.01, // g/cm³
    standardTolerance: "± 0.15 mm",
    minWallThickness: "0.8 mm",
    leadTime: "24 - 48 Hours",
    surfaceFinish: "Matte Bead Blasted / Vapor Smoothed",
    tags: ["High Durability", "Chemical Resistant", "Complex Geometry", "No Supports"],
    colorOptions: ["Charcoal Grey", "Deep Black", "Off-White"],
    idealFor: "Functional enclosures, robotic joints, snap-fit components, automotive ducting"
  },
  {
    id: "pa11-sls",
    name: "PA 11 (Bio-based Nylon)",
    technology: "SLS",
    category: "Polymers",
    description: "Ductile, impact-resistant bio-polyamide derived from castor oil. Outstanding elasticity and crash test performance.",
    tensileStrength: 52,
    hdt: 182,
    elongation: 45,
    density: 1.04,
    standardTolerance: "± 0.15 mm",
    minWallThickness: "0.9 mm",
    leadTime: "2 - 3 Days",
    surfaceFinish: "Standard Sintered / Dyed Black",
    tags: ["High Impact", "Bio-Compatible", "High Elongation"],
    colorOptions: ["Black", "Natural White"],
    idealFor: "Crash-proof drone arms, prosthetics, wearables, snap-fits"
  },
  {
    id: "peek-fdm",
    name: "PEEK (Polyetheretherketone)",
    technology: "FDM",
    category: "High-Performance",
    description: "Ultra-high performance semi-crystalline polymer with extreme thermal stability, flame retardance, and metal-replacement strength.",
    tensileStrength: 100,
    hdt: 250,
    elongation: 15,
    density: 1.30,
    standardTolerance: "± 0.20 mm",
    minWallThickness: "1.2 mm",
    leadTime: "3 - 5 Days",
    surfaceFinish: "Milled Ra 3.2 / Annealed",
    tags: ["Ultra High Temp", "Metal Replacement", "Sterilizable", "Aerospace"],
    colorOptions: ["Natural Beige", "Black"],
    idealFor: "Aerospace brackets, semiconductor manifolds, surgical implants, oil & gas seals"
  },
  {
    id: "ultem-9085-fdm",
    name: "ULTEM™ 9085 (PEI Resin)",
    technology: "FDM",
    category: "High-Performance",
    description: "Flame-retardant high-performance thermoplastic with FAR 25.853 aerospace flammability rating and high strength-to-weight ratio.",
    tensileStrength: 68,
    hdt: 153,
    elongation: 6,
    density: 1.34,
    standardTolerance: "± 0.20 mm",
    minWallThickness: "1.2 mm",
    leadTime: "2 - 4 Days",
    surfaceFinish: "Fine Layer Smooth",
    tags: ["Flame Retardant (V0)", "Aerospace Certified", "High Strength"],
    colorOptions: ["Tan", "Black"],
    idealFor: "Aircraft cabin components, rail transit enclosures, high-voltage isolators"
  },
  {
    id: "sla-tough-resin",
    name: "Tough ABS-Like 100",
    technology: "SLA",
    category: "Resins",
    description: "Engineering-grade photopolymer simulating injection molded ABS. Excellent surface finish with crisp geometric edges.",
    tensileStrength: 55,
    hdt: 68,
    elongation: 22,
    density: 1.15,
    standardTolerance: "± 0.08 mm",
    minWallThickness: "0.6 mm",
    leadTime: "24 - 48 Hours",
    surfaceFinish: "Ultra-Smooth Ra 0.8 / Clear Coat",
    tags: ["High Precision", "Smooth Surface", "Snap-fit Prototyping"],
    colorOptions: ["Translucent Grey", "White", "Jet Black"],
    idealFor: "High-detail master patterns, optical prototypes, consumer product housings"
  },
  {
    id: "sla-high-temp",
    name: "High-Temp Ceramic Resin",
    technology: "SLA",
    category: "Resins",
    description: "Ceramic-filled resin engineered to withstand extreme heat loads under low mechanical stress without deformation.",
    tensileStrength: 75,
    hdt: 238,
    elongation: 2,
    density: 1.25,
    standardTolerance: "± 0.08 mm",
    minWallThickness: "0.7 mm",
    leadTime: "2 - 3 Days",
    surfaceFinish: "Polished Ceramic-like",
    tags: ["Heat Deflection > 230°C", "Thermal Testing", "Rigid"],
    colorOptions: ["Matte White"],
    idealFor: "Hot air manifolds, environmental test fixtures, autoclave molds"
  },
  {
    id: "alu-6061-cnc",
    name: "Aluminum 6061-T6",
    technology: "CNC",
    category: "Metals",
    description: "Standard aerospace and mechanical engineering aluminum alloy with high strength, excellent weldability, and superior machinability.",
    tensileStrength: 310,
    hdt: 300,
    elongation: 12,
    density: 2.70,
    standardTolerance: "± 0.025 mm",
    minWallThickness: "0.8 mm",
    leadTime: "3 - 5 Days",
    surfaceFinish: "As-Machined (Ra 1.6), Type II Anodized, Bead Blasted",
    tags: ["ISO 2768-m", "Anodizable", "High Strength-to-Weight", "5-Axis"],
    colorOptions: ["Clear Anodized", "Black Anodized", "Blue Anodized", "Raw Metal"],
    idealFor: "Structural aerospace fittings, camera mounts, motor chassis, robotics frames"
  },
  {
    id: "ss-316l-cnc",
    name: "Stainless Steel 316L",
    technology: "CNC",
    category: "Metals",
    description: "Marine-grade austenitic chromium-nickel-molybdenum stainless steel with outstanding corrosion resistance and biocompatibility.",
    tensileStrength: 580,
    hdt: 550,
    elongation: 40,
    density: 8.00,
    standardTolerance: "± 0.025 mm",
    minWallThickness: "1.0 mm",
    leadTime: "4 - 7 Days",
    surfaceFinish: "Electropolished / Passivated",
    tags: ["Marine Grade", "Corrosion Resistant", "Biocompatible", "High Strength"],
    colorOptions: ["Natural Metallic", "Electropolished Mirror"],
    idealFor: "Medical devices, food-grade chemical valves, marine hardware, pressure vessels"
  },
  {
    id: "ti-6al4v-dmls",
    name: "Titanium Ti-6Al-4V (Grade 5)",
    technology: "DMLS",
    category: "Metals",
    description: "Direct Metal Laser Sintered titanium alloy delivering extraordinary tensile strength, low weight, and biocompatibility.",
    tensileStrength: 1050,
    hdt: 800,
    elongation: 10,
    density: 4.43,
    standardTolerance: "± 0.05 mm",
    minWallThickness: "0.5 mm",
    leadTime: "5 - 8 Days",
    surfaceFinish: "Stress Relieved / Micro-blasted / CNC finish",
    tags: ["1050 MPa Tensile", "Aerospace Grade", "Additive Metal", "Extreme Lightness"],
    colorOptions: ["Sintered Titanium Grey"],
    idealFor: "Turbine impellers, bone fixation implants, generative aerospace brackets"
  },
  {
    id: "tpu-95a-fdm",
    name: "TPU 95A Elastomer",
    technology: "FDM",
    category: "Elastomers",
    description: "Thermoplastic polyurethane with rubber-like flexibility, high tear resistance, and dynamic vibration damping.",
    tensileStrength: 39,
    hdt: 60,
    elongation: 550,
    density: 1.20,
    standardTolerance: "± 0.25 mm",
    minWallThickness: "1.5 mm",
    leadTime: "24 - 48 Hours",
    surfaceFinish: "Textured Rubber",
    tags: ["550% Elongation", "Shock Absorbing", "Tear Proof"],
    colorOptions: ["Black", "Translucent", "High-Vis Red"],
    idealFor: "Custom gaskets, shock dampers, soft-touch robotic grippers, cable boots"
  },
  {
    id: "sheet-alu-5052",
    name: "Aluminum 5052-H32 Sheet",
    technology: "Sheet Metal",
    category: "Metals",
    description: "High fatigue strength sheet alloy with excellent formability and superior resistance to saltwater atmosphere.",
    tensileStrength: 228,
    hdt: 200,
    elongation: 18,
    density: 2.68,
    standardTolerance: "± 0.10 mm",
    minWallThickness: "0.8 - 6.0 mm",
    leadTime: "2 - 4 Days",
    surfaceFinish: "Deburred / Powder Coated / Chromate Conversion",
    tags: ["Laser Cut", "CNC Brake Formed", "PEM Hardware Ready"],
    colorOptions: ["Black Powder Coat", "Clear Chromate", "Brushed"],
    idealFor: "19-inch server chassis, electrical junction boxes, industrial brackets"
  }
];

if (typeof module !== 'undefined') {
  module.exports = { MATERIALS_DATA };
}
