import { PrismaClient } from '@prisma/client';
import { randomBytes } from 'node:crypto';
import { hashPassword } from '../../auth/password.service';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding CAM LABS PostgreSQL database...');

  // Seed Users
  const user1 = await prisma.user.upsert({
    where: { email: 'e.vance@vance-robotics.tech' },
    update: {},
    create: {
      id: 'persona-1',
      name: 'Dr. Elena Vance',
      email: 'e.vance@vance-robotics.tech',
      role: 'ENGINEER',
      accountStatus: 'ACTIVE',
      passwordHash: await hashPassword(process.env.SEED_DEMO_PASSWORD || randomBytes(32).toString('hex')),
      company: 'Vance Autonomous Systems Inc.',
      phone: '+1 (415) 890-2144',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
      tier: 'Enterprise Pro',
      address: '742 Innovation Way, Bldg 4, San Francisco, CA 94107',
      taxId: 'US-88491024',
      preferences: {
        units: 'mm',
        toleranceStandard: 'ISO 2768-fine (±0.05 mm)',
        dfmNotifications: true,
        dispatchAlerts: true,
      },
    },
  });

  // Seed Materials (full production catalog; PostgreSQL is the source of truth)
  const materials = [
    {
      id: 'pla',
      name: 'PLA',
      technology: 'FDM',
      pricePerUnit: 2, priceUnit: 'EGP/g',
      category: 'Polymers',
      description: 'The most popular 3D printing material, great for prototypes, decorations, and everyday parts. Offers high detail and smooth surfaces.',
      tensileStrength: 50,
      hdt: 58,
      elongation: 6,
      density: 1.24,
      standardTolerance: '± 0.20 mm',
      minWallThickness: '0.8 mm',
      leadTime: '24 - 48 Hours',
      surfaceFinish: 'Standard FDM',
      tags: ['Default', 'High Detail', 'Indoor Use'],
      colorOptions: ['Any', 'Black', 'White', 'Red', 'Blue', 'Green', 'Yellow', 'Orange', 'Purple', 'Gray'],
      idealFor: 'Prototypes, decorations, and everyday parts',
    },
    {
      id: 'abs',
      name: 'ABS',
      technology: 'FDM',
      pricePerUnit: 3, priceUnit: 'EGP/g',
      category: 'Polymers',
      description: 'A tough engineering-grade material commonly used in automotive and industrial products. Heat resistant up to ~95–105°C with good water resistance.',
      tensileStrength: 48,
      hdt: 100,
      elongation: 10,
      density: 1.04,
      standardTolerance: '± 0.20 mm',
      minWallThickness: '0.8 mm',
      leadTime: '24 - 48 Hours',
      surfaceFinish: 'Standard FDM',
      tags: ['Engineering Grade', 'Heat Resistant', 'Industrial'],
      colorOptions: ['Any', 'Black', 'White', 'Red', 'Blue', 'Green', 'Yellow', 'Orange', 'Purple', 'Gray'],
      idealFor: 'Automotive and industrial products',
    },
    {
      id: 'petg',
      name: 'PETG',
      technology: 'FDM',
      pricePerUnit: 3, priceUnit: 'EGP/g',
      category: 'Polymers',
      description: 'A strong and durable material that combines easy printing with good heat and weather resistance. Great for functional parts, containers, and outdoor applications.',
      tensileStrength: 50,
      hdt: 75,
      elongation: 20,
      density: 1.27,
      standardTolerance: '± 0.20 mm',
      minWallThickness: '0.8 mm',
      leadTime: '24 - 48 Hours',
      surfaceFinish: 'Standard FDM',
      tags: ['Weather Resistant', 'Functional', 'Outdoor Use'],
      colorOptions: ['Any', 'Black', 'White', 'Red', 'Blue', 'Green', 'Yellow', 'Orange', 'Purple', 'Gray'],
      idealFor: 'Functional parts, containers, and outdoor applications',
    },
    {
      id: 'tpu',
      name: 'TPU',
      technology: 'FDM',
      pricePerUnit: 4, priceUnit: 'EGP/g',
      category: 'Elastomers',
      description: 'A flexible rubber-like material used for seals, gaskets, and parts requiring impact resistance. Heat resistant up to ~110–120°C with excellent water and UV resistance.',
      tensileStrength: 39,
      hdt: 115,
      elongation: 350,
      density: 1.21,
      standardTolerance: '± 0.25 mm',
      minWallThickness: '0.9 mm',
      leadTime: '24 - 48 Hours',
      surfaceFinish: 'Standard FDM Flexible',
      tags: ['Flexible', 'Vibration Damping', 'Abrasion Resistant'],
      colorOptions: ['Any', 'Black', 'Natural', 'Translucent'],
      idealFor: 'Seals, gaskets, strain reliefs, and impact-resistant parts',
    },
    {
      id: 'pa12-sls',
      name: 'PA 12 (Nylon 12)',
      technology: 'SLS',
      category: 'Polymers',
      description: 'Versatile engineering thermoplastic with balanced mechanical properties, high chemical resistance, and excellent fatigue resistance.',
      tensileStrength: 48,
      hdt: 175,
      elongation: 18,
      density: 1.01,
      standardTolerance: '± 0.15 mm',
      minWallThickness: '0.8 mm',
      leadTime: '24 - 48 Hours',
      surfaceFinish: 'Matte Bead Blasted / Vapor Smoothed',
      tags: ['High Durability', 'Chemical Resistant', 'Complex Geometry', 'No Supports'],
      colorOptions: ['Charcoal Grey', 'Deep Black', 'Off-White'],
      idealFor: 'Functional enclosures, robotic joints, snap-fit components, automotive ducting',
    },
    {
      id: 'pa11-sls',
      name: 'PA 11 (Bio-based Nylon)',
      technology: 'SLS',
      category: 'Polymers',
      description: 'Bio-based nylon derived from castor oil with superior impact resistance, ductility, and fatigue endurance.',
      tensileStrength: 52,
      hdt: 182,
      elongation: 45,
      density: 1.02,
      standardTolerance: '± 0.15 mm',
      minWallThickness: '0.8 mm',
      leadTime: '2 - 3 Days',
      surfaceFinish: 'Matte Bead Blasted / Vapor Smoothed',
      tags: ['High Impact', 'Flexible', 'Complex Geometry', 'No Supports'],
      colorOptions: ['Off-White', 'Deep Black'],
      idealFor: 'Living hinges, wear-resistant parts, protective casings, aerospace ducting',
    },
    {
      id: 'peek-fdm',
      name: 'PEEK (Polyetheretherketone)',
      technology: 'FDM',
      category: 'High-Performance',
      description: 'Ultra-high performance semi-crystalline polymer with extreme thermal stability, flame retardance, and metal-replacement strength.',
      tensileStrength: 100,
      hdt: 250,
      elongation: 15,
      density: 1.30,
      standardTolerance: '± 0.20 mm',
      minWallThickness: '1.2 mm',
      leadTime: '3 - 5 Days',
      surfaceFinish: 'Milled Ra 3.2 / Annealed',
      tags: ['Ultra High Temp', 'Metal Replacement', 'Sterilizable', 'Aerospace'],
      colorOptions: ['Natural Beige', 'Black'],
      idealFor: 'Aerospace brackets, semiconductor manifolds, surgical implants, oil & gas seals',
    },
    {
      id: 'ultem-9085-fdm',
      name: 'ULTEM™ 9085 (PEI Resin)',
      technology: 'FDM',
      category: 'High-Performance',
      description: 'Flame-retardant PEI resin with exceptional strength-to-weight ratio and FST certification for aerospace interiors.',
      tensileStrength: 68,
      hdt: 153,
      elongation: 4,
      density: 1.27,
      standardTolerance: '± 0.20 mm',
      minWallThickness: '1.0 mm',
      leadTime: '2 - 4 Days',
      surfaceFinish: 'Milled Ra 3.2 / Sanded',
      tags: ['Aerospace Certified', 'Flame Retardant', 'High Strength'],
      colorOptions: ['Amber', 'Black'],
      idealFor: 'Aircraft interior brackets, ducting, thermal enclosures, stowage components',
    },
    {
      id: 'sla-tough-resin',
      name: 'Tough ABS-Like 100',
      technology: 'SLA',
      category: 'Resins',
      description: 'ABS-like photopolymer with high toughness and dimensional accuracy for functional prototyping.',
      tensileStrength: 55,
      hdt: 68,
      elongation: 25,
      density: 1.12,
      standardTolerance: '± 0.10 mm',
      minWallThickness: '0.5 mm',
      leadTime: '24 - 48 Hours',
      surfaceFinish: 'Smooth Semi-Gloss / Vapor Smoothed',
      tags: ['Smooth Surface', 'Snap-Fit', 'Fine Detail'],
      colorOptions: ['White', 'Grey', 'Black', 'Clear'],
      idealFor: 'Fit-testing, snap-fits, brackets, master patterns for casting',
    },
    {
      id: 'sla-high-temp',
      name: 'High-Temp Ceramic Resin',
      technology: 'SLA',
      category: 'Resins',
      description: 'Ceramic-filled photopolymer with high heat deflection for thermal management applications.',
      tensileStrength: 75,
      hdt: 238,
      elongation: 3,
      density: 1.6,
      standardTolerance: '± 0.10 mm',
      minWallThickness: '0.5 mm',
      leadTime: '2 - 3 Days',
      surfaceFinish: 'Smooth Matte',
      tags: ['High Temp', 'Ceramic', 'Fine Detail'],
      colorOptions: ['Grey', 'Tan'],
      idealFor: 'Mold masters, thermal fixtures, RTV tooling masters, airflow guides',
    },
    {
      id: 'alu-6061-cnc',
      name: 'Aluminum 6061-T6',
      technology: 'CNC',
      category: 'Metals',
      description: 'Standard aerospace and mechanical engineering aluminum alloy with high strength, excellent weldability, and superior machinability.',
      tensileStrength: 310,
      hdt: 300,
      elongation: 12,
      density: 2.70,
      standardTolerance: '± 0.025 mm',
      minWallThickness: '0.8 mm',
      leadTime: '3 - 5 Days',
      surfaceFinish: 'As-Machined (Ra 1.6), Type II Anodized, Bead Blasted',
      tags: ['ISO 2768-m', 'Anodizable', 'High Strength-to-Weight', '5-Axis'],
      colorOptions: ['Clear Anodized', 'Black Anodized', 'Blue Anodized', 'Raw Metal'],
      idealFor: 'Structural aerospace fittings, camera mounts, motor chassis, robotics frames',
    },
    {
      id: 'ss-316l-cnc',
      name: 'Stainless Steel 316L',
      technology: 'CNC',
      category: 'Metals',
      description: 'Austenitic stainless steel with outstanding corrosion resistance for marine and medical applications.',
      tensileStrength: 580,
      hdt: 550,
      elongation: 40,
      density: 8.00,
      standardTolerance: '± 0.025 mm',
      minWallThickness: '1.0 mm',
      leadTime: '4 - 7 Days',
      surfaceFinish: 'As-Machined (Ra 1.6), Passivated, Electropolished',
      tags: ['Corrosion Resistant', 'Medical Grade', 'Sanitary'],
      colorOptions: ['Raw Metal', 'Electropolished'],
      idealFor: 'Marine components, medical instrumentation, food-processing fixtures, pump housings',
    },
    {
      id: 'ti-6al4v-dmls',
      name: 'Titanium Ti-6Al-4V (Grade 5)',
      technology: 'DMLS',
      category: 'Metals',
      description: 'Alpha-beta titanium alloy with the highest strength-to-weight ratio in the catalog for aerospace and biomedical hardware.',
      tensileStrength: 1050,
      hdt: 800,
      elongation: 10,
      density: 4.42,
      standardTolerance: '± 0.10 mm',
      minWallThickness: '0.8 mm',
      leadTime: '5 - 8 Days',
      surfaceFinish: 'As-Built / Bead Blasted / CNC Finish Machined',
      tags: ['Aerospace', 'Medical Implant', 'Lightweight', 'Corrosion Resistant'],
      colorOptions: ['Silvery Grey'],
      idealFor: 'Aerospace brackets, surgical instruments, motorsport components, heat exchangers',
    },
    {
      id: 'tpu-95a-fdm',
      name: 'TPU 95A Elastomer',
      technology: 'FDM',
      category: 'Elastomers',
      description: 'Flexible thermoplastic polyurethane elastomer with excellent abrasion resistance and rebound.',
      tensileStrength: 39,
      hdt: 60,
      elongation: 350,
      density: 1.21,
      standardTolerance: '± 0.25 mm',
      minWallThickness: '1.0 mm',
      leadTime: '24 - 48 Hours',
      surfaceFinish: 'Matte Flexible Finish',
      tags: ['Flexible', 'Vibration Damping', 'Abrasion Resistant'],
      colorOptions: ['Black', 'Natural', 'Neon Translucent'],
      idealFor: 'Gaskets, vibration isolators, cable strain reliefs, soft-touch grips',
    },
    {
      id: 'sheet-alu-5052',
      name: 'Aluminum 5052-H32 Sheet',
      technology: 'Sheet Metal',
      category: 'Metals',
      description: 'Work-hardened aluminum sheet with excellent formability and corrosion resistance for precision sheet-metal fabrications.',
      tensileStrength: 228,
      hdt: 200,
      elongation: 12,
      density: 2.68,
      standardTolerance: '± 0.10 mm',
      minWallThickness: '0.5 mm',
      leadTime: '2 - 4 Days',
      surfaceFinish: 'Mill Finish / Brushed / Powder Coated',
      tags: ['Formable', 'Corrosion Resistant', 'Welding', 'Cost Effective'],
      colorOptions: ['Mill Finish', 'White Powder Coat', 'Black Powder Coat'],
      idealFor: 'Enclosures, panels, brackets, heat shields, chassis covers',
    },
  ];

  for (const m of materials) {
    await prisma.material.upsert({
      where: { id: m.id },
      update: {},
      create: m,
    });
  }

  // Seed the internal CAM LABS manufacturing cell (no external providers)
  await prisma.manufacturer.upsert({
    where: { companyName: 'CAM LABS Internal Manufacturing Cell' },
    update: {},
    create: {
      companyName: 'CAM LABS Internal Manufacturing Cell',
      contactPerson: 'CAM LABS Operations',
      email: 'ops@cam-labs.internal',
      phone: '+20 (0) 2 0000 0000',
      location: 'Cairo, Egypt',
      address: 'CAM LABS Production Campus, Cairo',
      supportedTechnologies: ['FDM', 'SLS', 'SLA', 'CNC_MILLING', 'DMLS', 'SHEET_METAL'],
      supportedMaterials: ['PLA', 'ABS', 'PETG', 'TPU', 'PA 12 (Nylon 12)', 'PEEK', 'Aluminum 6061-T6', 'Stainless Steel 316L', 'Titanium Ti-6Al-4V'],
      capacity: 50,
      availability: 'AVAILABLE',
      currentOrders: 0,
      completedOrders: 0,
      performanceRating: 5.0,
      status: 'ACTIVE',
      notes: 'Default in-house CAM LABS production cell. Orders are never routed to external providers.',
    },
  });

  // Seed Orders
  await prisma.order.upsert({
    where: { id: 'CAM-2026-8894' },
    update: {},
    create: {
      id: 'CAM-2026-8894',
      userId: user1.id,
      partName: 'Turbine_Manifold_v3.step',
      technology: 'CNC Machining',
      material: 'Aluminum 6061-T6 (Anodized Black)',
      quantity: 12,
      date: '2026-08-12',
      estDelivery: '2026-08-18',
      status: 'In Production',
      statusBadge: 'badge-blue',
      progressStep: 2,
      totalCost: '1,480.00 EGP',
      tolerance: '±0.025 mm',
      trackingNum: 'DHL-EXPRESS-992014812',
      history: [
        { step: 'CAD Geometry Verification', date: 'Aug 12, 09:30', done: true, desc: 'Automated DFM check passed.' },
        { step: 'CAM Toolpath Generation', date: 'Aug 12, 14:15', done: true, desc: '5-Axis G-code optimized.' },
        { step: 'Precision CNC Milling', date: 'Aug 13, 08:00', done: true, desc: 'Billet milling underway.' },
        { step: 'CMM Laser Dimensional QA', date: 'Pending', done: false, desc: 'Zeiss CMM touch-probe inspection.' },
        { step: 'Dispatched via Express Courier', date: 'Pending', done: false, desc: 'Direct courier dispatch.' },
      ],
    },
  });

  console.log('CAM LABS Database seeded successfully.');
}

main()
  .catch((e) => {
    console.error('Seeding error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
