import { chromium } from 'playwright';
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport: { width: 1440, height: 900 } });
const page = await ctx.newPage();
page.on('console', (m) => console.log('CONSOLE:', m.type(), m.text().slice(0, 160)));
page.on('pageerror', (e) => console.log('PAGEERROR:', String(e).slice(0, 200)));
await ctx.request.post('http://localhost:3000/api/v1/auth/login', { data: { email: 'qamatrix1789997801861@example.com', password: 'TestPass123!' } });
await page.goto('http://localhost:3000/#dashboard', { waitUntil: 'networkidle' });
await page.waitForTimeout(2500);
console.log('hash:', await page.evaluate(() => location.hash));
console.log('main id:', await page.evaluate(() => document.querySelector('main')?.id));
console.log('has dashboard-view:', await page.evaluate(() => !!document.querySelector('[class*="dashboard-view"], .dash-page, .oc-list')));
await browser.close();
