import { chromium } from 'playwright';
const BASE = 'http://localhost:3000';
const EMAIL = 'qa-1789955654676@example.com';
const PASS = 'QaPass12';
const browser = await chromium.launch();
const context = await browser.newContext({ viewport: { width: 1440, height: 900 }, colorScheme: 'dark' });
const page = await context.newPage();
const errs = [];
page.on('console', (msg) => { if (msg.type() === 'error' && !msg.text().includes('style property')) errs.push(msg.text().slice(0, 120)); });
await context.request.post(`${BASE}/api/v1/auth/login`, { data: { email: EMAIL, password: PASS } });
await page.goto(`${BASE}#/dashboard`, { waitUntil: 'networkidle' });
await page.waitForSelector('.dash-page', { timeout: 20000 });
await page.waitForTimeout(900);
console.log('theme:', await page.evaluate(() => document.documentElement.dataset.theme));
await page.screenshot({ path: '/tmp/qa3-dash-dark.png' });
await page.goto(`${BASE}#/account`, { waitUntil: 'networkidle' });
await page.waitForTimeout(800);
await page.click('.account-country-button');
await page.waitForTimeout(500);
await page.fill('.account-country-search input', 'Egypt');
await page.screenshot({ path: '/tmp/qa3-phone-dark.png' });
await page.keyboard.press('Escape');
await page.click("button.account-nav-item:has-text('Security')");
await page.waitForTimeout(400);
await page.screenshot({ path: '/tmp/qa3-security-dark.png' });
await context.close();
await browser.close();
console.log('ERRORS:', errs.length ? errs : 'none');
